# Builds the project

name: XcodeBuild

on: [push]

jobs:
  Build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: List Xcodes
      run: ls -n /Applications/ | grep Xcode*
      
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_12_beta.app"

    - name: Xcode Build
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        project: Project SF.xcodeproj
        scheme: Project SF
        destination: platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro
        action: build
     
