# Tests the project

name: Test

on: [push]

jobs:
  Build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_12_beta.app"

    - name: Xcode Build
      run: "xcodebuild -workspace Calculator.xcworkspace -scheme Project\ SF -destination platform=iOS\ Simulator,OS=14.0,name=iPhone\ 11\ Pro clean test | xcpretty"
     
